backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "About the Instructor", name: "about", widget: "text" }
          - { label: "Pricing", name: "pricing", widget: "text" }
          - { label: "Lesson Plan", name: "lessonplan", widget: "text" }
